...

diff --git a/all b/all
--- a/all
+++ b/all
@@ -1,23 +1,23 @@
 ___X_CMD_ROOT="$HOME/.x-cmd" && (
-    BOOT="$HOME/.x-cmd/.boot/boot"
+    BOOT="$HOME/.x-cmd/.boot/boot";
     if [ -f "$BOOT" ]; then
-        . "$BOOT"
-        exit 0
+        . "$BOOT";
+        exit 0;
     fi
 
-    URL="https://raw.githubusercontent.com/x-cmd/x-cmd/main/dist/all.tgz"
+    URL="https://raw.githubusercontent.com/x-cmd/x-cmd/main/dist/all.tgz";
 
-    D="$___X_CMD_ROOT"
-    mkdir -p "$D"
-    cd "$D"
+    D="$___X_CMD_ROOT";
+    mkdir -p "$D";
+    cd "$D";
     if curl --fail "$URL" >"all.tgz" 2>/dev/null; then
-        tar xf "all.tgz"
+        tar xf "all.tgz";
     else
-        printf "Fail to download: %s\n" "$URL" >&2
-        exit 1
+        printf "Fail to download: %s\n" "$URL" >&2;
+        exit 1;
     fi
 ) && {
-    ___X_CMD_IN_CHINA_NET=
-    . "${___X_CMD_ROOT}/xrc/latest"
-    x boot setup
+    ___X_CMD_IN_CHINA_NET= ;
+    . "${___X_CMD_ROOT}/xrc/latest";
+    x boot setup;
 }
