update: xx

diff --git a/x8 b/x8
--- a/x8
+++ b/x8
@@ -1,2 +1,8 @@
 
-XX=x8 eval "$(curl https://get.x-cmd.com/xx)"
+if command -v curl >/dev/null; then
+    XX=x8 eval "$(curl https://get.x-cmd.com/xx)";
+elif command -v wget >/dev/null; then
+    XX=x8 eval "$(wget -O- https://get.x-cmd.com/xx)";
+else
+    printf "%s\n" "command not found ==> curl wget " >&2;
+fi;
